export const FETCH_APPS_FULFILLED = 'FETCH_APPS_FULFILLED';
export const FETCH_APPS_REJECTED = 'FETCH_APPS_REJECTED';
export const FETCHING_APPS = 'FETCHING_APPS';
export const FETCH_APPS_NOT_AUTHENTICATED = 'FETCH_APPS_NOT_AUTHENTICATED';
export const FETCH_APP_FULFILLED = 'FETCH_APP_FULFILLED';

export const FETCH_FOUNDATIONS_FULFILLED = 'FETCH_FOUNDATIONS_FULFILLED';
export const FETCH_FOUNDATIONS_REJECTED = 'FETCH_FOUNDATIONS_REJECTED';
export const FETCH_APP_DETAILS_FULFILLED = 'FETCH_APP_DETAILS_FULFILLED';
export const FETCH_APP_DETAILS_REJECTED = 'FETCH_APP_DETAILS_REJECTED';
export const LOGIN_FOUNDATION = 'LOGIN_FOUNDATION';
export const LOGIN_FOUNDATION_REJECTED = 'LOGIN_FOUNDATION_REJECTED';
export const LOGOUT_FOUNDATION = 'LOGOUT_FOUNDATION';
export const FOUNDATION_LOGIN_MODAL_OPEN_STATE = 'FOUNDATION_LOGIN_MODAL_OPEN_STATE';
export const LOAD_FOUNDATION_INFO = 'LOAD_FOUNDATION_INFO';

export const SELECT_APPLIST = 'SELECT_APPLIST';
export const SEARCH_FIELD_UPDATED = 'SEARCH_FIELD_UPDATED';
export const SELECT_APP = 'SELECT_APP';

export const DONE_REFRESHING_FOUNDATION_TOKEN = 'DONE_REFRESHING_FOUNDATION_TOKEN';
export const REFRESHING_FOUNDATION_TOKEN = 'REFRESHING_FOUNDATION_TOKEN';
export const REFRESHED_FOUNDATION_TOKEN = 'REFRESHED_FOUNDATION_TOKEN';
export const TOGGLE_FOUNDATION = 'TOGGLE_FOUNDATION';

export const TOGGLE_BUILDPACK = 'TOGGLE_BUILDPACK';
export const TOGGLE_APP_STATE = 'TOGGLE_APP_STATE';
export const SELECT_APP_FAILED = 'SELECT_APP_FAILED';

export const FETCH_CISERVERS_FULFILLED = 'FETCH_CISERVERS_FULFILLED';
export const LOGIN_CISERVER = 'LOGIN_CISERVER';
export const LOGIN_CISERVER_REJECTED = 'LOGIN_CISERVER_REJECTED'
export const LOGOUT_CISERVER = 'LOGOUT_CISERVER'
export const CISERVER_LOGIN_MODAL_OPEN_STATE = 'CISERVER_LOGIN_MODAL_OPEN_STATE'
export const LOGIN_PIPELINE_REJECTED = 'LOGIN_PIPELINE_REJECTED'

export const LOADING_PIPELINES = 'LOADING_PIPELINES'
export const LOAD_PIPELINES_FULFILLED = 'LOAD_PIPELINES_FULFILLED'
export const LOAD_PIPELINES_REJECTED = 'LOAD_PIPELINES_REJECTED'

export const DONE_REFRESHING_CISERVER_TOKEN = 'DONE_REFRESHING_CISERVER_TOKEN';
export const REFRESHING_CISERVER_TOKEN = 'REFRESHING_CISERVER_TOKEN';
export const REFRESHED_CISERVER_TOKEN = 'REFRESHED_CISERVER_TOKEN';
export const TOGGLE_CISERVER = 'TOGGLE_CISERVER';
export const SORT_UPDATED = 'SORT_UPDATED';
