export const FETCH_APPS_FULFILLED = 'FETCH_APPS_FULFILLED';
export const FETCH_APPS_REJECTED = 'FETCH_APPS_REJECTED';
export const FETCHING_APPS = 'FETCHING_APPS';
export const FETCH_APPS_NOT_AUTHENTICATED = 'FETCH_APPS_NOT_AUTHENTICATED';

export const FETCH_FOUNDATIONS_FULFILLED = 'FETCH_FOUNDATIONS_FULFILLED';
export const FETCH_FOUNDATIONS_REJECTED = 'FETCH_FOUNDATIONS_REJECTED';
export const FETCH_APP_DETAILS_FULFILLED = 'FETCH_APP_DETAILS_FULFILLED';
export const FETCH_APP_DETAILS_REJECTED = 'FETCH_APP_DETAILS_REJECTED';
export const LOGIN_FOUNDATION = 'LOGIN_FOUNDATION';
export const LOGIN_FOUNDATION_REJECTED = 'LOGIN_FOUNDATION_REJECTED';
export const LOGOUT_FOUNDATION = 'LOGOUT_FOUNDATION';
export const FOUNDATION_LOGIN_MODAL_OPEN_STATE = 'FOUNDATION_LOGIN_MODAL_OPEN_STATE';

export const SELECT_APPLIST = 'SELECT_APPLIST';
export const SEARCH_FIELD_UPDATED = 'SEARCH_FIELD_UPDATED';
export const SELECT_APP = 'SELECT_APP';

export const DONE_REFRESHING_FOUNDATION_TOKEN = 'DONE_REFRESHING_FOUNDATION_TOKEN';
export const REFRESHING_FOUNDATION_TOKEN = 'REFRESHING_FOUNDATION_TOKEN';
export const REFRESHED_FOUNDATION_TOKEN = 'REFRESHED_FOUNDATION_TOKEN';
export const TOGGLE_FOUNDATION = 'TOGGLE_FOUNDATION';

export const TOGGLE_BUILDPACK = 'TOGGLE_BUILDPACK';
export const TOGGLE_APP_STATE = 'TOGGLE_APP_STATE';
export const SELECT_APP_FAILED = 'SELECT_APP_FAILED';

export const FETCH_PIPELINES_FULFILLED = 'FETCH_PIPELINES_FULFILLED';
export const LOGIN_PIPELINE = 'LOGIN_PIPELINE';
export const LOGIN_PIPELINE_REJECTED = 'LOGIN_PIPELINE_REJECTED'
export const LOGOUT_PIPELINE = 'LOGOUT_PIPELINE'
export const PIPELINE_LOGIN_MODAL_OPEN_STATE = 'PIPELINE_LOGIN_MODAL_OPEN_STATE'

export const DONE_REFRESHING_PIPELINE_TOKEN = 'DONE_REFRESHING_PIPELINE_TOKEN';
export const REFRESHING_PIPELINE_TOKEN = 'REFRESHING_PIPELINE_TOKEN';
export const REFRESHED_PIPELINE_TOKEN = 'REFRESHED_PIPELINE_TOKEN';
export const TOGGLE_PIPELINE = 'TOGGLE_PIPELINE';
